include $(HOME)/make.dir/makefile.std

all:applserv gprsserv snmpserv

applserv:appl_util.o appl_callproc.o appl_qryandset.o appl_alarm.o appl_gprs.o appl_td.o appl_process.o applserver.o  
	$(CCLINK) -L$(HOME)/lib -lmobile2g -L$(HOME)/lib -lcgprotcl

gprsserv:appl_util.o appl_callproc.o appl_qryandset.o appl_alarm.o appl_gprs.o appl_td.o appl_process.o gprsserver.o  
	$(CCLINK) -L$(HOME)/lib -lmobile2g -L$(HOME)/lib -lcgprotcl
	
snmpserv:appl_util.o appl_qryandset.o appl_alarm.o appl_gprs.o appl_td.o appl_process.o snmpserver.o  
	$(CCLINK) -L$(HOME)/lib -lmobile2g -L$(HOME)/lib -lcgprotcl
monthproc:monthproc.o appl_qryandset.o appl_util.o appl_alarm.o appl_gprs.o appl_td.o
	$(CCLINK) -L$(HOME)/lib -lmobile2g -L$(HOME)/lib -lcgprotcl
